stages:
  prepare:
    cmd: python -m src.prepare
    deps:
      - data/raw/telco_churn.csv
      - src/prepare.py
      - src/features.py
      - src/utils.py
    params:
      - seed
      - data.raw
      - split
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: python -m src.train
    deps:
      - data/processed/train.csv
      - src/train.py
      - src/features.py
      - src/utils.py
    params:
      - seed
      - train
    outs:
      - models/model.joblib

  evaluate:
    cmd: python -m src.evaluate
    deps:
      - data/processed/test.csv
      - models/model.joblib
      - src/evaluate.py
      - src/features.py
      - src/utils.py
    metrics:
      - metrics.json:
          cache: false
